# Generated by Django 6.0.6 on 2026-07-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='Иконка')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Категория инструментов',
                'verbose_name_plural': 'Категории инструментов',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ToolPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название инструмента')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='URL инструмента')),
                ('h1', models.CharField(max_length=180, verbose_name='H1 заголовок')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='Иконка')),
                ('meta_title', models.CharField(max_length=180, verbose_name='SEO Title')),
                ('meta_description', models.TextField(verbose_name='SEO Description')),
                ('robots', models.CharField(default='index, follow', max_length=50, verbose_name='Robots')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный инструмент')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='tools.toolcategory', verbose_name='Категория')),
                ('related_tools', models.ManyToManyField(blank=True, to='tools.toolpage', verbose_name='Похожие инструменты')),
            ],
            options={
                'verbose_name': 'Страница инструмента',
                'verbose_name_plural': 'Страницы инструментов',
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='tools_toolp_slug_4fd268_idx'), models.Index(fields=['is_published'], name='tools_toolp_is_publ_70b9af_idx'), models.Index(fields=['is_popular'], name='tools_toolp_is_popu_a031b2_idx')],
            },
        ),
    ]
