# Generated by Django 6.0.6 on 2026-07-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpage',
            name='badge',
            field=models.CharField(blank=True, max_length=80, verbose_name='Бейдж / метка'),
        ),
        migrations.AddField(
            model_name='toolpage',
            name='section',
            field=models.CharField(blank=True, max_length=100, verbose_name='Раздел внутри категории'),
        ),
    ]
